import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./ui/home.module.css"
import Image from 'next/image'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen min-w-screen`}>
        <Image src="/images/logo.png" className={`${styles.logo}`} width={300} height={40} alt="Intensament3d"/>
        {children}
        </body>
    </html>
  );
}
